### ISSUE TITLE
New Stream Deck software broke plugin

### ISSUE THREAD

**Issue by Crunchmeister1** [nguyenquyhy/Flight-Tracker-StreamDeck#96] opened 2020-12-14 21:15 UTC
Just updated to the new Stream Deck software. It seems that it's gone and broken the plugin. It no longer connects.

**Comment by nguyenquyhy** [comment] 2020-12-14 21:16
Can you share the logs at `%appdata%\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin\flightstreamdeck*.log`?

**Comment by Crunchmeister1** [comment] 2020-12-14 21:18
Attached it my log. Seems to be in the infinite death spiral. Haven't seen it do that since your last update. 

[flightstreamdeck20201214_001.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/5691625/flightstreamdeck20201214_001.log)

**Comment by Crunchmeister1** [comment] 2020-12-14 21:19
2020-12-14 16:18:15.063 -05:00 [ERR] Incompatible array count 8, expected 19. Skipping received data
2020-12-14 16:18:15.175 -05:00 [ERR] Incompatible array count 8, expected 19. Skipping received data
2020-12-14 16:18:15.282 -05:00 [ERR] Incompatible array count 8, expected 19. Skipping received data
2020-12-14 16:18:15.375 -05:00 [ERR] Incompatible array count 8, expected 19. Skipping received data

That looks like it could be something...

**Comment by Crunchmeister1** [comment] 2020-12-14 21:20
It seems to be somewhat working. Sometimes. It will take commands at times. Other times, pressing buttons has no effect. XFer from the comms panel doesn't seem to be working at all. It acts just like ENTER does, putting the new frequency in standby.

**Comment by nguyenquyhy** [comment] 2020-12-14 21:23
Yah there seems to be some issues with Xfer recently. I think I saw it too. We didn't touch that part so I don't suppose the problem is from the plugin, but I will look into this.

Do you notice issues with other button press?

**Comment by nguyenquyhy** [comment] 2020-12-14 21:25
> 2020-12-14 16:18:15.063 -05:00 [ERR] Incompatible array count 8, expected 19. Skipping received data
> 2020-12-14 16:18:15.175 -05:00 [ERR] Incompatible array count 8, expected 19. Skipping received data
> 2020-12-14 16:18:15.282 -05:00 [ERR] Incompatible array count 8, expected 19. Skipping received data
> 2020-12-14 16:18:15.375 -05:00 [ERR] Incompatible array count 8, expected 19. Skipping received data

By the way, those are not really an issue. This should be when you switch from 1 page to another. There is a short period when we delay the SimConnect variable registration (so as to not spamming registration for each button and instead register all buttons at once), so the expected number of variables on the page does not match the number of registered variables.

**Comment by Crunchmeister1** [comment] 2020-12-14 21:27
> Do you notice issues with other button press?

It's erratic because it keeps disconnecting and reconnecting. WHen it works, it seems to work ok as far as I can tell.

**Comment by rmroc451** [comment] 2020-12-14 21:28
> Yah there seems to be some issues with Xfer recently. I think I saw it too.

I think we were talking about that last night @nguyenquyhy. I'll see if I can toss some more logging in and track it down.

We haven't touched that since it went in.

**Comment by nguyenquyhy** [comment] 2020-12-14 22:05
I just tried Xfer again and realize the issue I am having: I press Xfer in the numpad without typing any number. Is that the same as what you are experiencing?

I intentionally let the button do nothing in that case when I first add the feature. Should I change it to transfer regardless?

**Comment by rmroc451** [comment] 2020-12-14 22:08
I'd say hitting xfer on an entry would do nothing. Just quick press the button normally, and it will flip them.

What I was seeing, was you typed a value in, hit xfer the deck would flash back to the previous profile and it did not change.

**Comment by mutoo2013** [comment] 2021-01-11 18:28
> Just updated to the new Stream Deck software. It seems that it's gone and broken the plugin. It no longer connects.

i have same problem for weeks，

now 
steamdeck 4.9.2.13193
FlightTracker 0.23

when i drag flighttracker button in board, streamdeck was broken
i cant edit any flighttracker button

i dont know what should i do....  i used flighttracker just for one week, then stream deck broken when i edit or drag any flighttracker button...

@nguyenquyhy @rmroc451 

thanks for help,  what should i do next?

**Comment by nguyenquyhy** [comment] 2021-01-11 19:23
@mutoo2013 Can you share the logs at %appdata%\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin\flightstreamdeck*.log?

**Comment by mutoo2013** [comment] 2021-01-12 03:15
> @mutoo2013 Can you share the logs at %appdata%\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin\flightstreamdeck*.log?

2021-01-12 11:13:52.033 +08:00 [INF] Initialize with args: C:\Users\Yuus\AppData\Roaming\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin\FlightStreamDeck.AddOn.dll|-port|28196|-pluginUUID|61E06A547A44CCF5DC5333CE69C2C326|-registerEvent|registerPlugin|-info|{"application":{"language":"en","platform":"windows","version":"4.9.2.13193"},"devicePixelRatio":1,"devices":[{"id":"E3B86990870D72DABC6BD5AEC28B455D","name":"StreamDeck","size":{"columns":5,"rows":3},"type":0}],"plugin":{"version":"0.23"}}

**Comment by mutoo2013** [comment] 2021-01-12 03:17
> @mutoo2013 Can you share the logs at %appdata%\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin\flightstreamdeck*.log?

>`11:13:50.463                     epl                               dbgcommand():                                   using log file 'C:\Users\Yuus\AppData\Roaming\Elgato\StreamDeck\logs\StreamDeck0.log'
11:13:50.464                     StreamDeck                        main():                                         Compiled with Qt 5.14.2 ; SSL: OpenSSL 1.1.1d  10 Sep 2019
11:13:50.465                     StreamDeck                        main():                                         Runtime SSL Supported: 1
11:13:50.466                     StreamDeck                        main():                                         Runtime SSL version used: OpenSSL 1.1.1d  10 Sep 2019
11:13:50.739                     StreamDeck                        EGQTTranslationManager::LoadLocalizations():    Could not load the 'en_US' localization
11:13:50.739                     StreamDeck                        main():                                         Using preferences from \HKEY_CURRENT_USER\Software\Elgato Systems GmbH\StreamDeck
11:13:50.742                     StreamDeck                        ESDCustomPluginCommunication::start():          Using port 28196 to communicate with plugins
11:13:50.749                     StreamDeck                        ESDPluginManager::LoadPluginsInFolder():        Loading custom plugins...
11:13:50.749                     StreamDeck                        ESDPluginManager::LoadPluginsInFolder():        Loading tech.flighttracker.streamdeck.sdPlugin...
11:13:51.094                     StreamDeck                        ESDVSDServer::init():                           ### [SERVER] init
11:13:51.094                     StreamDeck                        ESDCUEHub::init():                              ### [CUESDK] init
11:13:51.100                     StreamDeck                        AccountMgr::InitializeAccountMgr():             AccountMgr initialized
11:13:51.100                     StreamDeck                        AccountMgr::ReloadAllAccountsFromPreferences(): Reload all accounts
11:13:51.100                     StreamDeck                        AccountMgr::RecreateServiceInstancesForType():  Recreate service instances for Twitter
11:13:51.100                     StreamDeck                        AccountMgr::RecreateServiceInstancesForType():  Recreate service instances for YouTube
11:13:51.100                     StreamDeck                        AccountMgr::RecreateServiceInstancesForType():  Recreate service instances for Streamlabs
11:13:51.100                     StreamDeck                        AccountMgr::RecreateServiceInstancesForType():  Recreate service instances for Twitch
11:13:51.101                     StreamDeck                        EGCAPILiteDLL::LoadDLL():                       Could not load EGCAPILite.dll
11:13:51.101                     StreamDeck                        EGCAPILiteDLL::LoadDLL():                       Loading EGCAPILite.dll from: C:\Program Files\Elgato\GameCapture\EGCAPILite.dll, result: 0
11:13:51.101                     StreamDeck                        EGCAPILiteDLL::Initialize():                    mInitializeFunc is not set
11:13:51.101                     StreamDeck                        GameCaptureSync::GameCaptureSync():             Unable to initialize Game Capture integration.
11:13:51.101                     StreamDeck                        MainWindow::ReloadProfiles():                   Flattening profiles in C:\Users\Yuus\AppData\Roaming\Elgato\StreamDeck\ProfilesV2
11:13:51.102                     StreamDeck                        MainWindow::ReloadProfiles():                   Loading profiles from C:\Users\Yuus\AppData\Roaming\Elgato\StreamDeck\ProfilesV2
11:13:51.102                     StreamDeck                        ESDProfileManager::LoadProfileAtPath():         Loading profile at path C:\Users\Yuus\AppData\Roaming\Elgato\StreamDeck\ProfilesV2\37D2E922-0B72-40FF-8ADB-54DFA01C57C0.sdProfile
11:13:51.102                     StreamDeck                        ESDProfileManager::LoadProfileAtPath():         Loading profile at path C:\Users\Yuus\AppData\Roaming\Elgato\StreamDeck\ProfilesV2\7A868375-08C5-4891-95E7-A6D5A1D6F182.sdProfile
11:13:51.103                     StreamDeck                        ESDProfileManager::LoadProfileAtPath():         Loading profile at path C:\Users\Yuus\AppData\Roaming\Elgato\StreamDeck\ProfilesV2\8B5A6C96-11EE-4D2F-AC74-8B01B4AB243F.sdProfile
11:13:51.105                     StreamDeck                        ESDProfile::AddSubProfile():                    Sub profile with uuid F7728D42-CE4A-4864-A3FF-0C8BC3040AF8 added to profile E5FA5D9E-85C6-4936-B76B-1EAB74CFFAFD
11:13:51.105                     StreamDeck                        ESDProfile::AddSubProfile():                    Sub profile with uuid C043B00D-3F20-4335-865A-0CE0A78A1741 added to profile 8B5A6C96-11EE-4D2F-AC74-8B01B4AB243F
11:13:51.105                     StreamDeck                        ESDProfile::AddSubProfile():                    Sub profile with uuid 89FED92C-E87B-46B7-889C-A81629DE371B added to profile 8B5A6C96-11EE-4D2F-AC74-8B01B4AB243F
11:13:51.105                     StreamDeck                        ESDProfile::AddSubProfile():                    Sub profile with uuid 28FDF886-953C-42B7-845F-D4F8B774FA0A added to profile 8B5A6C96-11EE-4D2F-AC74-8B01B4AB243F
11:13:51.105                     StreamDeck                        ESDProfile::AddSubProfile():                    Sub profile with uuid A9CE16BE-D429-4D6F-9548-4373D7C030BE added to profile 8B5A6C96-11EE-4D2F-AC74-8B01B4AB243F
11:13:51.105                     StreamDeck                        ESDProfile::AddSubProfile():                    Sub profile with uuid AD142B59-0EC0-4AE1-B3BA-D8F2CDC5C648 added to profile 8B5A6C96-11EE-4D2F-AC74-8B01B4AB243F
11:13:51.105                     StreamDeck                        ESDProfile::AddSubProfile():                    Sub profile with uuid 1B4BB19B-3AB0-44E0-AA21-5C69E9ED8BDC added to profile 8B5A6C96-11EE-4D2F-AC74-8B01B4AB243F
11:13:51.105                     StreamDeck                        ESDProfile::AddSubProfile():                    Sub profile with uuid C3D1E504-B819-4BDE-A105-099C0A0AF515 added to profile 8B5A6C96-11EE-4D2F-AC74-8B01B4AB243F
11:13:51.105                     StreamDeck                        ESDProfile::AddSubProfile():                    Sub profile with uuid E5FA5D9E-85C6-4936-B76B-1EAB74CFFAFD added to profile 8B5A6C96-11EE-4D2F-AC74-8B01B4AB243F
11:13:51.105                     StreamDeck                        ESDProfileManager::LoadProfileAtPath():         Loading profile at path C:\Users\Yuus\AppData\Roaming\Elgato\StreamDeck\ProfilesV2\D69F3F9C-A182-4254-BEBB-063CC0D885F1.sdProfile
11:13:51.105                     StreamDeck                        ESDProfile::AddSubProfile():                    Sub profile with uuid 3973443B-25FC-4433-B62B-21A33CCE9C45 added to profile D69F3F9C-A182-4254-BEBB-063CC0D885F1
11:13:51.105                     StreamDeck                        ESDProfile::AddSubProfile():                    Sub profile with uuid 824125DB-13A9-4366-B156-C76A102612FF added to profile D69F3F9C-A182-4254-BEBB-063CC0D885F1
11:13:51.106                     StreamDeck                        ESDProfileManager::LoadProfileAtPath():         Loading profile at path C:\Users\Yuus\AppData\Roaming\Elgato\StreamDeck\ProfilesV2\E49164DD-128C-4AB9-AAF2-9A6F9586A667.sdProfile
11:13:51.106                     StreamDeck                        ESDProfile::AddSubProfile():                    Sub profile with uuid AECAE9BF-2AF9-4D8D-81F0-B31B35F0B63D added to profile E49164DD-128C-4AB9-AAF2-9A6F9586A667
11:13:51.106                     StreamDeck                        ESDProfile::AddSubProfile():                    Sub profile with uuid 3F6EF5E1-0D11-4C38-A993-5CC8A84EE2CA added to profile E49164DD-128C-4AB9-AAF2-9A6F9586A667
11:13:51.140                     StreamDeck                        MainWindow::bootstrap():                        Start Stream Deck App -> Version: 4.9.2.13193
11:13:51.196                     StreamDeck                        MainWindow::bootstrap():                        All object init done!
11:13:51.197                     StreamDeck                        MainWindow::bootstrap():                        Running in high dpi mode: 0
11:13:51.197                     StreamDeck                        ESDSharedFileServer::ESDSharedFileServer():     mapfile location C:\ProgramData\Elgato\StreamDeck\STREAMDECKINTERNALSHM
11:13:51.261                     StreamDeck                        MainWindow::event():                            Wake up keypad(s).
11:13:51.350                     StreamDeck                        MainWindow::onKeyboardStatusChange():           Firmware version in device(@(1)[4057/96/AL36I1C05196]): 1.0.191203
11:13:51.350                     StreamDeck                        MainWindow::onKeyboardStatusChange():           Device connected, serial number: AL36I1C05196 and id: @(1)[4057/96/AL36I1C05196]
11:13:51.351                     StreamDeck                        MainWindow::ReloadProfiles():                   Loading profiles from C:\Users\Yuus\AppData\Roaming\Elgato\StreamDeck\ProfilesV2
11:13:51.351                     StreamDeck                        ESDProfileManager::LoadProfileAtPath():         Loading profile at path C:\Users\Yuus\AppData\Roaming\Elgato\StreamDeck\ProfilesV2\37D2E922-0B72-40FF-8ADB-54DFA01C57C0.sdProfile
11:13:51.352                     StreamDeck                        ESDProfileManager::LoadProfileAtPath():         Loading profile at path C:\Users\Yuus\AppData\Roaming\Elgato\StreamDeck\ProfilesV2\7A868375-08C5-4891-95E7-A6D5A1D6F182.sdProfile
11:13:51.352                     StreamDeck                        ESDProfileManager::LoadProfileAtPath():         Loading profile at path C:\Users\Yuus\AppData\Roaming\Elgato\StreamDeck\ProfilesV2\8B5A6C96-11EE-4D2F-AC74-8B01B4AB243F.sdProfile
11:13:51.354                     StreamDeck                        ESDProfile::AddSubProfile():                    Sub profile with uuid F7728D42-CE4A-4864-A3FF-0C8BC3040AF8 added to profile E5FA5D9E-85C6-4936-B76B-1EAB74CFFAFD
11:13:51.354                     StreamDeck                        ESDProfile::AddSubProfile():                    Sub profile with uuid C043B00D-3F20-4335-865A-0CE0A78A1741 added to profile 8B5A6C96-11EE-4D2F-AC74-8B01B4AB243F
11:13:51.354                     StreamDeck                        ESDProfile::AddSubProfile():                    Sub profile with uuid 89FED92C-E87B-46B7-889C-A81629DE371B added to profile 8B5A6C96-11EE-4D2F-AC74-8B01B4AB243F
11:13:51.354                     StreamDeck                        ESDProfile::AddSubProfile():                    Sub profile with uuid 28FDF886-953C-42B7-845F-D4F8B774FA0A added to profile 8B5A6C96-11EE-4D2F-AC74-8B01B4AB243F
11:13:51.354                     StreamDeck                        ESDProfile::AddSubProfile():                    Sub profile with uuid A9CE16BE-D429-4D6F-9548-4373D7C030BE added to profile 8B5A6C96-11EE-4D2F-AC74-8B01B4AB243F
11:13:51.354                     StreamDeck                        ESDProfile::AddSubProfile():                    Sub profile with uuid AD142B59-0EC0-4AE1-B3BA-D8F2CDC5C648 added to profile 8B5A6C96-11EE-4D2F-AC74-8B01B4AB243F
11:13:51.354                     StreamDeck                        ESDProfile::AddSubProfile():                    Sub profile with uuid 1B4BB19B-3AB0-44E0-AA21-5C69E9ED8BDC added to profile 8B5A6C96-11EE-4D2F-AC74-8B01B4AB243F
11:13:51.354                     StreamDeck                        ESDProfile::AddSubProfile():                    Sub profile with uuid C3D1E504-B819-4BDE-A105-099C0A0AF515 added to profile 8B5A6C96-11EE-4D2F-AC74-8B01B4AB243F
11:13:51.354                     StreamDeck                        ESDProfile::AddSubProfile():                    Sub profile with uuid E5FA5D9E-85C6-4936-B76B-1EAB74CFFAFD added to profile 8B5A6C96-11EE-4D2F-AC74-8B01B4AB243F
11:13:51.354                     StreamDeck                        ESDProfileManager::LoadProfileAtPath():         Loading profile at path C:\Users\Yuus\AppData\Roaming\Elgato\StreamDeck\ProfilesV2\D69F3F9C-A182-4254-BEBB-063CC0D885F1.sdProfile
11:13:51.355                     StreamDeck                        ESDProfile::AddSubProfile():                    Sub profile with uuid 3973443B-25FC-4433-B62B-21A33CCE9C45 added to profile D69F3F9C-A182-4254-BEBB-063CC0D885F1
11:13:51.355                     StreamDeck                        ESDProfile::AddSubProfile():                    Sub profile with uuid 824125DB-13A9-4366-B156-C76A102612FF added to profile D69F3F9C-A182-4254-BEBB-063CC0D885F1
11:13:51.355                     StreamDeck                        ESDProfileManager::LoadProfileAtPath():         Loading profile at path C:\Users\Yuus\AppData\Roaming\Elgato\StreamDeck\ProfilesV2\E49164DD-128C-4AB9-AAF2-9A6F9586A667.sdProfile
11:13:51.356                     StreamDeck                        ESDProfile::AddSubProfile():                    Sub profile with uuid AECAE9BF-2AF9-4D8D-81F0-B31B35F0B63D added to profile E49164DD-128C-4AB9-AAF2-9A6F9586A667
11:13:51.356                     StreamDeck                        ESDProfile::AddSubProfile():                    Sub profile with uuid 3F6EF5E1-0D11-4C38-A993-5CC8A84EE2CA added to profile E49164DD-128C-4AB9-AAF2-9A6F9586A667
11:13:52.031                     StreamDeck                        MainWindow::event():                            Wake up keypad(s).
11:13:54.187                     StreamDeck                        ESDCustomPluginCommunication::onMessageReceived(): Plugin 61E06A547A44CCF5DC5333CE69C2C326 is now connected
11:13:56.170                     StreamDeck                        EGQTSWUpdateDialog::checkForUpdate():           Check for update 2: https://gc-updates.elgato.com/windows/sd-update/final/app-version-check.json
11:13:56.170                     StreamDeck                        EGQTSWUpdateDownloader::startDownload():        Download task name: Update File, file URL: https://gc-updates.elgato.com/windows/sd-update/final/app-version-check.json
11:13:59.481                     StreamDeck                        EGQTSWUpdateDialog::shouldUpdate():             current SW Ver: 4.9.2.13193, remote SW Ver: 4.9.2.13193
11:13:59.481                     StreamDeck                        EGQTSWUpdateDialog::handleUpdateFileDownloaded(): No update available
11:14:03.156                     StreamDeck                        ESDAppStoreManager::UpdateAppStorePlugins():    Check for Plugin Store updates
11:14:03.501                     StreamDeck                        MainWindow::event():                            Wake up keypad(s).
11:14:16.827                     StreamDeck                        Preference::DeviceStateChangedNotification():   Dev FW ver: 1.0.191203, Embed FW ver: 1.0.191203
11:14:16.827                     StreamDeck                        Preference::DeviceStateChangedNotification():   show update fw button: no
11:14:16.827                     StreamDeck                        Preference::DeviceStateChangedNotification():   Serial No: AL36I1C05196
11:14:16.829                     StreamDeck                        Preference::DeviceStateChangedNotification():   Dev FW ver: 1.0.191203, Embed FW ver: 1.0.191203
11:14:16.829                     StreamDeck                        Preference::DeviceStateChangedNotification():   show update fw button: no
11:14:16.829                     StreamDeck                        Preference::DeviceStateChangedNotification():   Serial No: AL36I1C05196
11:14:16.839                     StreamDeck                        Preference::DeviceStateChangedNotification():   Dev FW ver: 1.0.191203, Embed FW ver: 1.0.191203
11:14:16.839                     StreamDeck                        Preference::DeviceStateChangedNotification():   show update fw button: no
11:14:16.839                     StreamDeck                        Preference::DeviceStateChangedNotification():   Serial No: AL36I1C05196
11:14:28.362                     StreamDeck                        MainWindow::event():                            Wake up keypad(s).
11:14:34.852                     StreamDeck                        MainWindow::event():                            Wake up keypad(s).
11:14:37.357                     StreamDeck                        MainWindow::event():                            Wake up keypad(s).
11:14:39.887                     StreamDeck                        ESDActionsGridViewModel::onKeyPressed():        Key 3 pressed: com.elgato.streamdeck.profile.openchild
11:14:40.146                     StreamDeck                        ESDActionsGridViewModel::onKeyReleased():       Key 3 released: unknown`

**Comment by mutoo2013** [comment] 2021-01-16 09:49
maybe i find the problem.... 

there have two adminstrator user in my win，
i set another  “net user administrator /active:no”
all things be ok....

so this maybe Elgato‘s problem... so stupid...


@nguyenquyhy @Crunchmeister1

**Comment by nguyenquyhy** [comment] 2021-02-21 07:54
Close this for now as this seem to be a problem with Stream Deck software.

**Closed by nguyenquyhy** 2021-02-21 07:54 UTC
Labels: bug
