### ISSUE TITLE
Custom gauges are lagging

### ISSUE THREAD

**Issue by kintonc** [nguyenquyhy/Flight-Tracker-StreamDeck#39] opened 2020-10-24 21:26 UTC
**Description of the issue & expected behavior**
My custom gauges are frequently lagging by 10-15 seconds. Ex: if I am accelerating from 100 knots to 150 knots, my indicators will lag and be 15 seconds behind.

**Stream Deck Plugin and MSFS version**
Flight Tracker Streamdeck 0.10
MSFS 2020, 1.9.5.0

Example of gauges:
AIRSPEED_INDICATED
PLANE_ALTITUDE
VERTICAL_SPEED

**Steps to reproduce the issue**
1. Start flying in FS2020 with the Streamdeck plugin enabled
2. Custom gauges will lag 10-15 seconds

**Comment by nguyenquyhy** [comment] 2020-10-24 23:50
This is very strange. I just tested all 3 values and did not get any delay. Do you mind sharing an export of your profile?

**Comment by kintonc** [comment] 2020-10-25 22:07
Here you go, thanks for looking!

 https://gofile.io/d/aNYOi6

**Comment by nguyenquyhy** [comment] 2020-10-26 05:52
I can't seem to reproduce the issue. You can check out a short recording here: https://gyazo.com/722ae6c62bf8daba23717d8edd797e98. The stream deck hang a bit at the beginning (I think due to the recording), but looks correct afterward.

Are you able to record something like that so I can have a better feel on how the issue looks like?

**Comment by nguyenquyhy** [comment] 2020-12-28 11:37
Close this issue for now due to lack of information and reproduction.

**Closed by nguyenquyhy** 2020-12-28 11:37 UTC
Labels: pending-information
