### ISSUE TITLE
Com and Nav buttons not working with latest v0.9

### ISSUE THREAD

**Issue by Virtual-Chris** [nguyenquyhy/Flight-Tracker-StreamDeck#35] opened 2020-10-19 03:40 UTC
My COM and NAV buttons are no longer displaying the frequencies as of v0.9,  Buttons just say "NAV1" or "COM1" with no other data showing.

**Comment by nguyenquyhy** [comment] 2020-10-19 05:30
Have you tried to restart Stream Deck? It works quite fine for me.

**Comment by Virtual-Chris** [comment] 2020-10-22 06:50
I cannot get com buttons to work since v.9. Everything else works fine. I will check the logs tomorrow.

**Comment by nguyenquyhy** [comment] 2020-10-22 06:54
My guess is that it is due to some invalid variables in other generic buttons (COM/NAV uses the same infrastructure) 😄. Generic buttons are not very robust when that happen.

Would be great if you can include the profile too.

**Comment by nguyenquyhy** [comment] 2020-10-25 04:40
Please try again with version 0.11 too.

**Comment by Virtual-Chris** [comment] 2020-10-26 00:31
As of v.12 My Com and Nav buttons still don't work... they don't display the frequencies on the button.  Also holding the button doesn't seem to load the profile to change the frequencies althought that is inconsistent.  uploading my profile in hopes you might figure out what's wrong.

[My Profile VC.zip](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/5436238/My.Profile.VC.zip)

**Comment by rmroc451** [comment] 2020-10-26 00:34
Any chance you have the properties of the nav/com set to be dependant on the batt and av master?

They won't show anything if those switches are off and the nav/com buttons are set to need them on. 

Just a thought

**Comment by nguyenquyhy** [comment] 2020-10-26 05:59
Looks normal to me:
![image](https://user-images.githubusercontent.com/1560418/97138416-1ed77480-1793-11eb-90e5-7b1aa55d37aa.png)

Can I have the log files at `%appdata%\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin\flightstreamdeck*.log`? Thanks.

**Comment by Virtual-Chris** [comment] 2020-10-26 06:57
Hmm. Will send tomorrow. Maybe it’s the G1000 mod I’m using?  Are you using this...

https://github.com/Working-Title-MSFS-Mods/fspackages/releases/tag/g1000-v0.3.1

Cheers,
-Chris.

On Oct 25, 2020, at 10:59 PM, Nguyễn Quý Hy <notifications@github.com> wrote:

﻿

Looks normal to me:
[image]<https://user-images.githubusercontent.com/1560418/97138416-1ed77480-1793-11eb-90e5-7b1aa55d37aa.png>

Can I have the log files at %appdata%\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin\flightstreamdeck*.log? Thanks.

**Comment by Virtual-Chris** [comment] 2020-10-27 02:01
Attached log...

[flightstreamdeck20201025.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/5442447/flightstreamdeck20201025.log)

**Comment by nguyenquyhy** [comment] 2020-10-27 07:07
The problem is the wrong unit we use for `KOHLSMAN SETTING HG`. The old FSX/P3D documentation states the unit as `Inches of Mercury, inHg` while in fact it should be `inHg`. I am fixing that and will release soon in the next version.

On a side note, if you set icon image with the built-in button image of Stream Deck, it will overwrite anything the plugin creates and the number (if any) won't show. You'll need to use the ON/OFF image feature at the bottom if you want to have both a custom background image and the number.

**Comment by nguyenquyhy** [comment] 2020-10-27 07:13
Fixed in version 0.14

**Closed by nguyenquyhy** 2020-10-27 07:13 UTC
Labels: pending-information
